modLoader="javafml"
loaderVersion="[34,)"
license="GNU LGPLv3"
logoFile="logo.png"
displayURL="https://github.com/gdavid04/MineTweaks"
authors="GDavid"
[[mods]]
modId="minetweaks"
version="${file.jarVersion}"
displayName="MineTweaks"
description='''
Small tweaks to the game
'''
[[dependencies.minetweaks]]
	modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.minetweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
